### ISSUE TITLE
脚本中ipv6代理gh-proxy-misakano7545.koyeb.app失效

### ISSUE THREAD

**Issue by lcajimmy** [daycat/stupid-simple-vmess#1]
https://gh-proxy-misakano7545.koyeb.app/ no longer work,
已经失效

**Comment by daycat** [comment]
你好，已收到，将更换自己的源来分发文件

**Comment by daycat** [comment]
fixed as of eb511bcda09b310d0c45f4ddf10b5e95a85195a8
