### ISSUE TITLE
无法注册证书

### ISSUE THREAD

**Issue by 283Gawin** [daycat/stupid-simple-vmess#2]
![image](https://user-images.githubusercontent.com/69577009/200128451-48c88a01-27b4-40c4-bf92-e243e2c8a471.png)
如图，证书创建失败，机子是Azure的b1，系统Ubuntu16.04

**Comment by xftesla** [comment]
+1，debian 9 板瓦工

**Comment by daycat** [comment]
抱歉，引起原因为域名分发api不稳定所导致，预计今晚修复

**Comment by daycat** [comment]
fixed as of eb511bcda09b310d0c45f4ddf10b5e95a85195a8
