### ISSUE TITLE
ERROR: The certificate of ‘api.daycat.space’ has expired.

### ISSUE THREAD

**Issue by xftesla** [daycat/stupid-simple-vmess#5]
![image](https://user-images.githubusercontent.com/42264527/211482772-0ed6e17e-ddf3-4efe-82c6-24d723b02cc7.png)
 
如图

**Comment by daycat** [comment]
Cannot replicate, please give more logs

**Comment by daycat** [comment]
Closed because of inactivity. Please reopen this thread if you run into this issue again.
